# Generated by Django 3.2.5 on 2021-08-25 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branchitem',
            old_name='branch_item_price',
            new_name='price',
        ),
    ]
