# Generated by Django 3.2.5 on 2021-08-26 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_item_price'),
        ('branches', '0002_rename_branch_item_price_branchitem_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='branchitem',
            unique_together={('item', 'branch')},
        ),
    ]
