# Generated by Django 3.2.5 on 2021-08-26 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_item_price'),
        ('branches', '0003_alter_branchitem_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='branchitem',
            unique_together={('item_id', 'branch_id')},
        ),
    ]
