# Generated by Django 3.2.5 on 2021-08-26 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_item_price'),
        ('branches', '0005_alter_branchitem_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='branchitem',
            unique_together={('item', 'branch')},
        ),
    ]
