# Generated by Django 3.2.5 on 2021-08-31 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_alter_branchitem_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='cities',
            new_name='city',
        ),
    ]
