# Generated by Django 3.2.5 on 2021-08-07 03:23

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_location_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=None, srid=4326),
        ),
    ]
