# Generated by Django 3.2.5 on 2021-08-08 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_auto_20210808_2119'),
        ('locations', '0004_alter_location_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='branches.city'),
        ),
    ]
