# Generated by Django 3.2.5 on 2021-08-31 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_auto_20210822_1921'),
        ('orders', '0011_alter_order_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='addresses.address'),
        ),
    ]
