# Generated by Django 3.2.5 on 2021-08-29 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_item_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['id']},
        ),
    ]
